"""Truncation-invariance tests for T6's as-of primitives (spec "Look-ahead"
acceptance criterion): f(T) on the full fixture store equals f(T) on a
store truncated to `known_at <= T`, for every probe generated by
`tests/lookahead/harness.py` around every distinct `known_at` in the
fixture (across every table, every security), for all four functions this
task implements.

Every as-of function returns a `polars.DataFrame`, sorted by its natural
key (`tradepartner.store.asof`'s module docstring), so two frames built
from equivalent data are compared with `DataFrame.equals` directly -- no
Python-side sort needed.

`universe_as_of` and `survivorship_gap` are later tasks (T13, T15) and are
not exercised here.

Audit round 1 additions (PR #69): a synthetic-store case with a REVISED
split (finding 5 -- a missing `corporate_actions.known_at` filter can't be
caught by the fixture alone, since none of its splits are revised), and a
harness meta-test (NIT 9) proving a function that ignores `known_at`
entirely fails the invariance assertion.

Audit round 2 addition (finding 1): a synthetic-store case with a
*revised bar* (not a revised corporate action) feeding a dividend's
prior-close ASOF-join lookup, catching a mutation that points that join
at raw `prices_daily` instead of the point-in-time `latest_bars` CTE.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator
from datetime import UTC, date, datetime
from typing import Any

import duckdb
import polars as pl
import pytest

from lookahead.harness import TruncatedStore, probe_timestamps
from tradepartner.store import schema
from tradepartner.store.asof import (
    adjusted_prices_as_of,
    dropped_dividends_as_of,
    facts_as_of,
    listings_as_of,
    prices_as_of,
)
from tradepartner.store.db import configure_connection, insert_row

AsOfFunc = Callable[..., pl.DataFrame]


@pytest.fixture
def truncated(fixture_store: duckdb.DuckDBPyConnection) -> Iterator[TruncatedStore]:
    """One `TruncatedStore` built from `fixture_store`, reused across every
    probe within a test (see `harness.TruncatedStore`'s docstring for why
    this is what makes the suite fast)."""
    store = TruncatedStore(fixture_store)
    try:
        yield store
    finally:
        store.close()


def _assert_invariant_over_every_probe(
    fixture_store: duckdb.DuckDBPyConnection,
    truncated: TruncatedStore,
    func: AsOfFunc,
    **kwargs: Any,
) -> None:
    for t in probe_timestamps(fixture_store):
        full = func(fixture_store, t, **kwargs)
        result = func(truncated.at(t), t, **kwargs)
        assert full.equals(result), f"{func.__name__} disagreed at T={t!r}"


@pytest.mark.parametrize("func", [prices_as_of, facts_as_of, listings_as_of])
def test_as_of_function_invariant_under_truncation(
    fixture_store: duckdb.DuckDBPyConnection, truncated: TruncatedStore, func: AsOfFunc
) -> None:
    _assert_invariant_over_every_probe(fixture_store, truncated, func)


@pytest.mark.parametrize("include_dividends", [False, True])
def test_adjusted_prices_as_of_invariant_under_truncation(
    fixture_store: duckdb.DuckDBPyConnection, truncated: TruncatedStore, include_dividends: bool
) -> None:
    _assert_invariant_over_every_probe(
        fixture_store, truncated, adjusted_prices_as_of, include_dividends=include_dividends
    )


def _bar(
    conn: duckdb.DuckDBPyConnection,
    security_id: str,
    session: date,
    close: float,
    *,
    known_at: datetime,
) -> None:
    insert_row(
        conn,
        "prices_daily",
        {
            "security_id": security_id,
            "session": session,
            "open": close,
            "high": close,
            "low": close,
            "close": close,
            "volume": 1000,
            "known_at": known_at,
            "ingested_at": known_at,
            "source": "test",
            "provenance": "bar",
        },
    )


def _action(
    conn: duckdb.DuckDBPyConnection,
    security_id: str,
    action_type: str,
    ex_date: date,
    ratio_or_amount: float,
    *,
    known_at: datetime,
) -> None:
    insert_row(
        conn,
        "corporate_actions",
        {
            "security_id": security_id,
            "action_type": action_type,
            "ex_date": ex_date,
            "ratio_or_amount": ratio_or_amount,
            "known_at": known_at,
            "ingested_at": known_at,
            "source": "test",
            "provenance": "action",
        },
    )


def test_revised_split_invariant_under_truncation() -> None:
    """Audit round 1, finding 5: the fixture store has no *revised* split
    (a second row for the same `(security_id, action_type, ex_date)` with
    a later `known_at`), so a bug that dropped `latest_actions`'
    `known_at <= t` filter in `adjusted_prices_as_of` would not be caught
    by the main invariance test at all -- `ROW_NUMBER() ... ORDER BY
    known_at DESC` would still pick a single "latest" row per key even
    with no `WHERE known_at <= t`, and every fixture split only has one
    row, so there is nothing for a missing filter to get wrong. This
    builds a synthetic store with a split whose revision is known
    *after* its own ex-date, at a different ratio, and runs the harness
    over it -- reproducing the mechanism T6's docstring in `harness.py`
    describes.
    """
    conn = duckdb.connect(":memory:")
    configure_connection(conn)
    schema.init_schema(conn)
    try:
        security_id = "SEC_REVISED_SPLIT"
        ex_date = date(2021, 3, 3)
        _bar(
            conn,
            security_id,
            date(2021, 3, 1),
            100.0,
            known_at=datetime(2021, 3, 1, 21, tzinfo=UTC),
        )
        _bar(
            conn,
            security_id,
            date(2021, 3, 2),
            100.0,
            known_at=datetime(2021, 3, 2, 21, tzinfo=UTC),
        )
        _bar(
            conn, security_id, date(2021, 3, 3), 50.0, known_at=datetime(2021, 3, 3, 21, tzinfo=UTC)
        )
        _bar(
            conn, security_id, date(2021, 3, 4), 50.0, known_at=datetime(2021, 3, 4, 21, tzinfo=UTC)
        )
        # First-seen: ratio 2.0, known the session before the ex-date.
        _action(
            conn,
            security_id,
            "split",
            ex_date,
            2.0,
            known_at=datetime(2021, 3, 2, 22, tzinfo=UTC),
        )
        # A later-discovered revision, known *after* the ex-date, at a
        # different ratio -- exactly the shape a missing known_at filter
        # would get wrong.
        _action(
            conn,
            security_id,
            "split",
            ex_date,
            4.0,
            known_at=datetime(2021, 3, 10, 12, tzinfo=UTC),
        )

        truncated_store = TruncatedStore(conn)
        try:
            for t in probe_timestamps(conn):
                full = adjusted_prices_as_of(conn, t)
                result = adjusted_prices_as_of(truncated_store.at(t), t)
                assert full.equals(result), f"disagreed at T={t!r}"
        finally:
            truncated_store.close()
    finally:
        conn.close()


def _build_revised_bar_dividend_store() -> duckdb.DuckDBPyConnection:
    """A synthetic store for `test_dividend_prior_close_invariant_under_
    truncation` and `test_dividend_prior_close_uses_bar_known_at_t`
    (audit round 2, finding 1): bars on `s1` and `s2`, a dividend with
    `ex_date = s3` known before `s3`, and a *revision* of `s2`'s close
    known after `s3` with a clearly different value. Nothing before this
    exercised a revision of the specific bar the dividend's `ASOF JOIN`
    prior-close lookup reads from.
    """
    conn = duckdb.connect(":memory:")
    configure_connection(conn)
    schema.init_schema(conn)
    security_id = "SEC_DIV_PRIOR_CLOSE_REVISED"
    s1, s2, s3 = date(2021, 5, 3), date(2021, 5, 4), date(2021, 5, 7)
    _bar(conn, security_id, s1, 100.0, known_at=datetime(2021, 5, 3, 21, tzinfo=UTC))
    _bar(conn, security_id, s2, 50.0, known_at=datetime(2021, 5, 4, 21, tzinfo=UTC))
    # A revision of s2's close, known well after the dividend's ex_date,
    # at a clearly different value than the original.
    _bar(conn, security_id, s2, 80.0, known_at=datetime(2021, 5, 12, 12, tzinfo=UTC))
    _action(
        conn,
        security_id,
        "dividend",
        s3,
        5.0,
        known_at=datetime(2021, 5, 6, 21, tzinfo=UTC),
    )
    return conn


def test_dividend_prior_close_invariant_under_truncation() -> None:
    """Audit round 2, finding 1: nothing before this checked that the
    dividend prior-close `ASOF JOIN` reads from `latest_bars` (point in
    time) rather than raw `prices_daily` (always the latest revision,
    regardless of T) -- a store with only one revision per bar, like the
    main fixture, can't distinguish the two, since there is nothing for a
    missing known_at filter to get wrong.
    """
    conn = _build_revised_bar_dividend_store()
    try:
        truncated_store = TruncatedStore(conn)
        try:
            for t in probe_timestamps(conn):
                full = adjusted_prices_as_of(conn, t, include_dividends=True)
                result = adjusted_prices_as_of(truncated_store.at(t), t, include_dividends=True)
                assert full.equals(result), f"disagreed at T={t!r}"
        finally:
            truncated_store.close()
    finally:
        conn.close()


def test_dividend_prior_close_uses_bar_known_at_t() -> None:
    """Direct assertion companion to the invariance test above: s1's
    adjusted close uses the *original* s2 close (50.0) before the
    revision's known_at, and the *revised* s2 close (80.0) after it.

    This was verified by hand to fail if `asof.py`'s `event_factor` CTE
    ASOF-joins the dividend's prior-close lookup against raw
    `prices_daily` instead of `latest_bars` (both closes become visible
    at every T once `prices_daily` itself has the row, so the "before the
    revision's known_at" case would wrongly see 80.0 too) -- that mutation
    was applied locally, confirmed to make this test fail, and reverted;
    it is not committed.
    """
    conn = _build_revised_bar_dividend_store()
    try:
        s1 = date(2021, 5, 3)

        before_revision = adjusted_prices_as_of(
            conn, datetime(2021, 5, 8, tzinfo=UTC), include_dividends=True
        )
        row = before_revision.filter(pl.col("session") == s1).row(0, named=True)
        # factor = 1 - 5.0 / 50.0 = 0.9 (original s2 close)
        assert row["close"] == pytest.approx(100.0 * 0.9)

        after_revision = adjusted_prices_as_of(
            conn, datetime(2021, 5, 13, tzinfo=UTC), include_dividends=True
        )
        row = after_revision.filter(pl.col("session") == s1).row(0, named=True)
        # factor = 1 - 5.0 / 80.0 = 0.9375 (revised s2 close)
        assert row["close"] == pytest.approx(100.0 * 0.9375)
    finally:
        conn.close()


def test_backfilled_prior_bar_does_not_rescue_a_stale_dividend_early() -> None:
    """Issue #72: a dividend whose only known prior bar is stale is dropped
    until the missing prior-session bar is backfilled; the backfill's own
    `known_at` (after the ex-date) gates the rescue, never its `session`.
    Checked with the harness for both the adjusted prices and the drop
    report, plus direct assertions either side of the backfill. This is
    `dropped_dividends_as_of`'s invariance test: no fixture dividend is
    ever dropped, so a fixture-wide run would compare empty frames only."""
    conn = duckdb.connect(":memory:")
    configure_connection(conn)
    schema.init_schema(conn)
    sid = "SEC_STALE_THEN_BACKFILLED"
    try:
        # 2021-06-01 is 7 XNYS sessions before the 2021-06-10 ex-date.
        _bar(conn, sid, date(2021, 6, 1), 40.0, known_at=datetime(2021, 6, 1, 21, tzinfo=UTC))
        _action(
            conn, sid, "dividend", date(2021, 6, 10), 2.0, known_at=datetime(2021, 6, 8, tzinfo=UTC)
        )
        # The 2021-06-09 bar arrives in a later backfill.
        _bar(conn, sid, date(2021, 6, 9), 50.0, known_at=datetime(2021, 6, 20, tzinfo=UTC))

        truncated_store = TruncatedStore(conn)
        try:
            for t in probe_timestamps(conn):
                for func, kwargs in (
                    (adjusted_prices_as_of, {"include_dividends": True}),
                    (dropped_dividends_as_of, {}),
                ):
                    full = func(conn, t, **kwargs)
                    result = func(truncated_store.at(t), t, **kwargs)
                    assert full.equals(result), f"{func.__name__} disagreed at T={t!r}"
        finally:
            truncated_store.close()

        before = datetime(2021, 6, 15, tzinfo=UTC)
        after = datetime(2021, 6, 21, tzinfo=UTC)
        june1 = pl.col("session") == date(2021, 6, 1)
        assert dropped_dividends_as_of(conn, before)["reason"].to_list() == ["stale_prior_bar"]
        assert adjusted_prices_as_of(conn, before, include_dividends=True).filter(june1)[
            "close"
        ].item() == pytest.approx(40.0)
        assert dropped_dividends_as_of(conn, after).height == 0
        # factor = 1 - 2.0 / 50.0 = 0.96
        assert adjusted_prices_as_of(conn, after, include_dividends=True).filter(june1)[
            "close"
        ].item() == pytest.approx(40.0 * 0.96)
    finally:
        conn.close()


def _leaky_prices_as_of(conn: duckdb.DuckDBPyConnection, t: datetime) -> pl.DataFrame:
    """A deliberately broken as-of function: it takes `t` but never
    filters by it. Used only by `test_harness_catches_a_function_that_
    ignores_known_at` (NIT 9) to prove the harness itself has teeth --
    if this function passed the invariance check, the harness would not
    be testing anything.
    """
    del t  # deliberately unused: the whole point is that this ignores T
    return conn.execute("SELECT * FROM prices_daily ORDER BY security_id, session").pl()


def test_harness_catches_a_function_that_ignores_known_at(
    fixture_store: duckdb.DuckDBPyConnection, truncated: TruncatedStore
) -> None:
    """NIT 9: the harness must be able to fail. `_leaky_prices_as_of`
    ignores `known_at <= t` entirely, so at an early probe (most of the
    fixture's rows not yet "truncated in") it must disagree between the
    untruncated store and the truncated one -- proving a real look-ahead
    bug would be caught, not just that a correct implementation passes.
    """
    t = probe_timestamps(fixture_store, ("prices_daily",))[0]
    full = _leaky_prices_as_of(fixture_store, t)
    result = _leaky_prices_as_of(truncated.at(t), t)
    assert not full.equals(result), "a function that ignores known_at should fail this check"
