"""Truncation-invariance tests for T6's as-of primitives (spec "Look-ahead"
acceptance criterion): f(T) on the full fixture store equals f(T) on a
store truncated to `known_at <= T`, for every probe generated by
`tests/lookahead/harness.py` around every distinct `known_at` in the
fixture (across every table, every security), for all four functions this
task implements.

Every as-of function returns a `polars.DataFrame`, sorted by its natural
key (`tradepartner.store.asof`'s module docstring), so two frames built
from equivalent data are compared with `DataFrame.equals` directly -- no
Python-side sort needed.

`universe_as_of` and `survivorship_gap` are later tasks (T13, T15) and are
not exercised here.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator
from typing import Any

import duckdb
import polars as pl
import pytest

from lookahead.harness import TruncatedStore, probe_timestamps
from tradepartner.store.asof import (
    adjusted_prices_as_of,
    facts_as_of,
    listings_as_of,
    prices_as_of,
)

AsOfFunc = Callable[..., pl.DataFrame]


@pytest.fixture
def truncated(fixture_store: duckdb.DuckDBPyConnection) -> Iterator[TruncatedStore]:
    """One `TruncatedStore` built from `fixture_store`, reused across every
    probe within a test (see `harness.TruncatedStore`'s docstring for why
    this is what makes the suite fast)."""
    store = TruncatedStore(fixture_store)
    try:
        yield store
    finally:
        store.close()


def _assert_invariant_over_every_probe(
    fixture_store: duckdb.DuckDBPyConnection,
    truncated: TruncatedStore,
    func: AsOfFunc,
    **kwargs: Any,
) -> None:
    for t in probe_timestamps(fixture_store):
        full = func(fixture_store, t, **kwargs)
        result = func(truncated.at(t), t, **kwargs)
        assert full.equals(result), f"{func.__name__} disagreed at T={t!r}"


@pytest.mark.parametrize("func", [prices_as_of, facts_as_of, listings_as_of])
def test_as_of_function_invariant_under_truncation(
    fixture_store: duckdb.DuckDBPyConnection, truncated: TruncatedStore, func: AsOfFunc
) -> None:
    _assert_invariant_over_every_probe(fixture_store, truncated, func)


@pytest.mark.parametrize("include_dividends", [False, True])
def test_adjusted_prices_as_of_invariant_under_truncation(
    fixture_store: duckdb.DuckDBPyConnection, truncated: TruncatedStore, include_dividends: bool
) -> None:
    _assert_invariant_over_every_probe(
        fixture_store, truncated, adjusted_prices_as_of, include_dividends=include_dividends
    )
